-- RA3: Schema de base de datos para proyecto Hibernate/JPA educativo
-- Base de datos H2 (compatible con PostgreSQL mode)
-- Estudiantes deben usar Hibernate/JPA para interactuar con estas tablas

-- Eliminar tablas si existen (para poder recrear en cada arranque)
-- El orden es importante por las foreign keys
DROP TABLE IF EXISTS ingredientes CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS npcs CASCADE;

-- ===== TABLA PRINCIPAL: npcs =====
-- Representa los personajes no jugables (NPCs) del juego
CREATE TABLE npcs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejorar rendimiento de consultas
CREATE INDEX idx_npcs_nombre ON npcs(nombre);
CREATE INDEX idx_npcs_activo ON npcs(activo);

-- ===== TABLA: pedidos =====
-- Cada NPC puede tener múltiples pedidos
-- Relación: NPC (1) → Pedidos (N)
CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_id BIGINT NOT NULL,
    comentario VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (npc_id) REFERENCES npcs(id) ON DELETE CASCADE
);

-- Índices para pedidos
CREATE INDEX idx_pedidos_npc_id ON pedidos(npc_id);

-- ===== TABLA: ingredientes =====
-- Cada pedido puede tener múltiples ingredientes
-- Relación: Pedido (1) → Ingredientes (N)
CREATE TABLE ingredientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cantidad INTEGER DEFAULT 1,
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);

-- Índices para ingredientes
CREATE INDEX idx_ingredientes_pedido_id ON ingredientes(pedido_id);
CREATE INDEX idx_ingredientes_nombre ON ingredientes(nombre);

-- ===== NOTAS PEDAGÓGICAS =====
-- 
-- RELACIONES IMPLEMENTADAS:
-- - NPC (1) → Pedidos (N): Un NPC puede tener muchos pedidos
-- - Pedido (1) → Ingredientes (N): Un pedido puede tener muchos ingredientes
--
-- CASCADE DELETE:
-- - Si se elimina un NPC, se eliminan automáticamente sus pedidos
-- - Si se elimina un pedido, se eliminan automáticamente sus ingredientes
--
-- DIFERENCIAS vs RA2 (JDBC):
-- - RA2: Los estudiantes escribían JOINs manualmente
-- - RA3: Hibernate genera los JOINs automáticamente con @OneToMany/@ManyToOne
